name: Keep Render Server Warm

on: 
  schedule:
    - cron: '*/10 * * * *' #calls the server every tens minutes

  workflow_dispatch: #allows for manual trigger

jobs:
  keep_warm:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Server
        run: |
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null --max-time 30 https://my-blog-server-bn2n.onrender.com)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Server returned HTTP status code $RESPONSE"
            exit 1
          fi 
